version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: api
    hostname: api
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7041
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd123 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/src/API.pfx
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/mssql-tools/bin
    volumes:
      - "./:/src"  
      - ~/.aspnet/https:/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "7041:8081"