apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30011  # this will expose the service on your host 
  type: NodePort